# Las file generated by CloudCompare have  Global Encoding set incorrectly as 1 when it should be 17
# https://gis.stackexchange.com/questions/413191/python-pdal-error-reading-format-1-4-las-file-readers-las-error-global-enco
# This script corrects the file

import sys
filename = sys.argv[1]
f = open(filename, "rb+")
f.seek(6)
f.write(bytes([17, 0, 0, 0]));
f.close()